README.md, docs/DeveloperGuide.md, docs/UserGuide.md
Update NFRs, codecov readme, dg use cases, value proposition, target user profile, user stories
=> Update NFRs, codecov readme, dg use cases, value proposition, target user profile

src/main/java/seedu/address/commons/util/StringUtil.java, src/main/java/seedu/address/model/Vehicle.java, src/main/java/seedu/address/model/entity/person/Customer.java, src/main/java/seedu/address/model/entity/shop/Shop.java, src/main/java/seedu/address/model/exception/VehicleNotFoundException.java, src/main/java/seedu/address/model/service/Appointment.java, src/main/java/seedu/address/model/service/Part.java, src/main/java/seedu/address/model/service/PartMap.java, src/main/java/seedu/address/model/service/Service.java, src/main/java/seedu/address/model/service/exception/InsufficientPartException.java, src/main/java/seedu/address/model/service/exception/OverwritePartException.java, src/main/java/seedu/address/model/service/exception/PartNotFoundException.java, src/test/java/seedu/address/commons/util/StringUtilTest.java
=> Add customers, vehicles, services

src/main/java/seedu/address/logic/parser/CliSyntax.java
=> Add command prefixes

src/main/java/seedu/address/model/ReadOnlyShop.java, src/main/java/seedu/address/model/entity/shop/Shop.java, src/main/java/seedu/address/model/service/Part.java, src/main/java/seedu/address/model/service/PartMap.java, src/main/java/seedu/address/model/service/PartType.java, src/main/java/seedu/address/model/service/Service.java, src/main/java/seedu/address/model/service/ServiceStatus.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedPart.java, src/main/java/seedu/address/storage/JsonAdaptedService.java, src/main/java/seedu/address/storage/JsonSerializableShop.java
- Storage handlers for Service and Part (Can Save and Read from json file)
- Storage handlers for Appointments/Technicians will be implemented much later, for v1.3 or v1.4 iterations
- Sample data available for services and parts
- Reading from and saving to json file works, works similarly to how addressbook data is saved and read
Merging this in allows us to start implement CRUD properly for Services and Parts
=> Update storage v1.1

docs/DeveloperGuide.md, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/AddCustomerCommand.java, src/main/java/seedu/address/logic/commands/AddPartCommand.java, src/main/java/seedu/address/logic/commands/AddServiceCommand.java, src/main/java/seedu/address/logic/commands/AddVehicleCommand.java, src/main/java/seedu/address/logic/commands/ClearCommand.java, src/main/java/seedu/address/logic/commands/Command.java, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/logic/commands/RedoCommand.java, src/main/java/seedu/address/logic/commands/RedoableCommand.java, src/main/java/seedu/address/logic/commands/StackUndoRedo.java, src/main/java/seedu/address/logic/commands/UndoCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java
Dev guide still need pics to be added. Will update later
=> Add undo and redo feature

docs/UserGuide.md, src/main/java/seedu/address/model/service/PartMap.java, src/main/java/seedu/address/model/service/exception/NegativeValueException.java, src/main/java/seedu/address/model/service/exception/PartLessThanZeroException.java
=> 62 userguide 63 validate

src/main/java/seedu/address/logic/idgen/IdGenerator.java
Need this to manually initialize IDs for sample data
=> Add setIdUsed methods

src/main/java/seedu/address/logic/Logic.java, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/commands/ListServicesCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/mapping/ServiceDataMap.java, src/main/java/seedu/address/model/service/PartMap.java, src/main/java/seedu/address/model/service/Service.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/ServiceCard.java, src/main/java/seedu/address/ui/ServiceListPanel.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/ServiceListCard.fxml, src/main/resources/view/ServiceListPanel.fxml, src/test/java/seedu/address/logic/commands/AddCommandTest.java
- Includes fixes for SampleData generator
- GUI for List services
- closes #30
=> Add List Services Command

src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/commands/AddCustomerCommand.java, src/main/java/seedu/address/logic/commands/AddServiceCommand.java, src/main/java/seedu/address/logic/commands/AddVehicleCommand.java, src/main/java/seedu/address/logic/parser/AddVehicleCommandParser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/mapping/CustomerVehicleMap.java, src/main/java/seedu/address/model/mapping/ServiceDataMap.java, src/main/java/seedu/address/model/mapping/VehicleDataMap.java, src/main/java/seedu/address/model/service/Service.java, src/main/java/seedu/address/model/service/Vehicle.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonSerializableShop.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java
- only works for customer, vehicle and service
- fixes #75
=> Add commands gui integration

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/AddPartToServiceCommand.java, src/main/java/seedu/address/logic/commands/AddTechnicianToServiceCommand.java, src/main/java/seedu/address/logic/parser/AddTechnicianCommandParser.java, src/main/java/seedu/address/logic/parser/AddTechnicianToServiceCommandParser.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/entity/shop/Shop.java, src/main/java/seedu/address/model/service/Service.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java
Could test much cos no listtechnicians yet but seems to work ok
#94
=> Add service technician

src/main/java/seedu/address/commons/core/Messages.java, src/main/java/seedu/address/logic/commands/TotalAppointmentCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/TotalAppointmentCommandParser.java, src/main/java/seedu/address/model/service/appointment/Appointment.java
I messed up the old one with merge conflicts...
=> Add TotalAppointment command feature

src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/logic/parser/FindCommandParser.java, src/main/java/seedu/address/model/Findable.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/entity/person/Customer.java, src/main/java/seedu/address/model/entity/person/Person.java, src/main/java/seedu/address/model/service/Service.java, src/main/java/seedu/address/model/service/Vehicle.java, src/main/java/seedu/address/model/service/appointment/Appointment.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/FindCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Updated existing find command to find anything
- new `Findable` interface that command interacts with
- only need to implement hasKeyword(String) method
- still thinking about how to implement for parts
=> Feature: find

src/main/java/seedu/address/logic/commands/AddPartToServiceCommand.java, src/main/java/seedu/address/logic/commands/AddTechnicianToAppointmentCommand.java, src/main/java/seedu/address/logic/commands/AddTechnicianToServiceCommand.java, src/main/java/seedu/address/logic/parser/AddTechnicianToAppointmentCommandParser.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/entity/shop/Shop.java, src/main/java/seedu/address/model/service/appointment/Appointment.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java
- support for assigning exisisting technicians to existing appointments
=> Command: AddTechnicianToAppointment

docs/DeveloperGuide.md, docs/UserGuide.md
Reverts AY2223S2-CS2103-W17-4/tp#109
=> Revert "Julio doc changes"

docs/UserGuide.md, src/test/java/seedu/address/logic/commands/RedoCommandTest.java
- Add redocommand Test 
- Improved UG undo phrasing 
- Didn't make viewcustomer/vehicle/etc undoable cuz it wont work. tried it already.
=> Add redoCommandTest

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/AddVehicleCommand.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java
Clearing some easy to fix bugs from PE-D
- closes #136 
- closes #128
- closes #130
- closes #124
=> Minor fixes

docs/DeveloperGuide.md, docs/team/junlee1991.md
- Cut down on similar use cases.
#87
=> Update Dg use cases

src/main/java/seedu/address/model/entity/shop/Shop.java
Was iterating over list while updating
=> Fix potential bug

src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/UserPrefs.java, src/main/java/seedu/address/model/entity/shop/Shop.java
allows us to use `assertCommandSuccess(..)` for JUnit Tests
=> Add equals and hashcode overrides for Junit test purposes

src/main/java/seedu/address/model/entity/shop/Shop.java, src/main/java/seedu/address/model/entity/shop/exception/TechnicianAlreadyAssignedException.java, src/main/java/seedu/address/model/entity/shop/exception/TechnicianNotAssignedException.java
=> Fix bug not checking technician already/haven't assigned
